---
title: "03.Ordinations_R"
author: "Elliott Schmidt"
date: "`r Sys.Date()`"
output: github_document
---


```{r warning=FALSE, message=FALSE}
library(tidyverse) 
library(ggpubr)
```

```{r}
gatk_filteredv3_pca <- read_table("C:/Users/jc527762/OneDrive - James Cook University/PhD dissertation/Data/Chapter2_Genetics/03.Ordinations_NEW/gatk.filteredv3.pca.eigenvec")

region.list <- factor(rep(c("CORE", "CHAUVEL","LEADING","HERON","LEADING","TORRES STRAIT","REEF HQ"), c(24, 8, 8, 8, 16, 15, 3)))  
pop <- factor(rep(c("SUDBURY","TONGUE", "VLASSOF", "CHAUVEL","COCKERMOUTH","HERON","KESWICK","StBEES","TORRES STRAIT","REEF HQ"), 
                  c(9,7,8, 8, 8, 8, 8, 8, 15, 3)))  
mycol=c("#FF5722","#D32F2F","dodgerblue","#00BCD4","#455A64","#212121") 
mycol.pop=c("#FF5722","#FF9900","#FFCC00","#CC9900","#3366FF","#6699FF","#66CCFF","#00BCD4","#455A64","#212121")
```

```{r}
gatk_filteredv3_pca2 <- gatk_filteredv3_pca |> 
  cbind(region.list, pop) |> 
  rename(Sample = `#IID`, 
         region = region.list) |> 
  mutate(region=fct_relevel(region, c("TORRES STRAIT","CORE","LEADING","CHAUVEL","HERON","REEF HQ")),
         pop = fct_relevel(pop, c("TORRES STRAIT","SUDBURY","TONGUE", "VLASSOF",
                                  "COCKERMOUTH","KESWICK","StBEES","CHAUVEL","HERON","REEF HQ")))
```

```{r fig.height=4, fig.width=10}
pc12 <-ggplot(gatk_filteredv3_pca2, aes(x=PC1, y=PC2, color=region)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC1 (30.52%)") + ylab("PC2 (22.09%)") +
  theme_classic() + 
  scale_color_manual(values = mycol) +
  theme(legend.position = "none")

pc13 <-ggplot(gatk_filteredv3_pca2, aes(x=PC1, y=PC3, color=region)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC1 (30.52%)") + ylab("PC3 (4.46%)") +
  theme_classic() +  
  scale_color_manual(values = mycol) +
  theme(legend.position = "none")

pc23 <-ggplot(gatk_filteredv3_pca2, aes(x=PC2, y=PC3, color=region)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC2 (22.09%)") + ylab("PC3 (4.46%)") +
  theme_classic() +  
  scale_color_manual(values = mycol) +
  theme(legend.position = "none")

ggarrange(pc12,pc13,pc23, 
          nrow = 1, 
          ncol = 3, 
          common.legend = TRUE)
```

```{r fig.height=4, fig.width=10}
pc12 <-ggplot(gatk_filteredv3_pca2, aes(x=PC1, y=PC2, color=pop)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC1 (30.52%)") + ylab("PC2 (22.09%)") +
  theme_classic() + 
  scale_color_manual(values = mycol.pop) +
  theme(legend.position = "none")

pc13 <-ggplot(gatk_filteredv3_pca2, aes(x=PC1, y=PC3, color=pop)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC1 (30.52%)") + ylab("PC3 (4.46%)") +
  theme_classic() +  
  scale_color_manual(values = mycol.pop) +
  theme(legend.position = "none")

pc23 <-ggplot(gatk_filteredv3_pca2, aes(x=PC2, y=PC3, color=pop)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC2 (22.09%)") + ylab("PC3 (4.46%)") +
  theme_classic() +  
  scale_color_manual(values = mycol.pop) +
  theme(legend.position = "none")

ggarrange(pc12,pc13,pc23, 
          nrow = 1, 
          ncol = 3, 
          common.legend = TRUE)
```


```{r}
gatk_filteredv3_pca <- read_table("C:/Users/jc527762/OneDrive - James Cook University/PhD dissertation/Data/Chapter2_Genetics/03.Ordinations_NEW/gatk.filtered.relaxed_studywide_primary.pca.eigenvec")

region.list <- factor(rep(c("LEADING", "CORE"), c(32, 24)))  
mycol=c("#D32F2F","dodgerblue")  
pop <- factor(rep(c("KESWICK","CHAUVEL","COCKERMOUTH","StBEES","SUDBURY","TONGUE", "VLASSOF"), 
                  c(8,8,8, 8, 9, 7, 8)))  
mycol=c("#FF5722","#D32F2F","dodgerblue","#00BCD4","#455A64","#212121") 
mycol.pop=c("#3366FF","#6699FF","#66CCFF","#00BCD4","#FF5722","#FF9900","#FFCC00")
gatk_filteredv3_pca$region <- region.list
gatk_filteredv3_pca$pop <- pop
```

```{r fig.height=4, fig.width=10}
pc12 <-ggplot(gatk_filteredv3_pca, aes(x=PC1, y=PC2, color=pop)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC1 (30.52%)") + ylab("PC2 (22.09%)") +
  theme_classic() + 
  scale_color_manual(values = mycol.pop) +
  theme(legend.position = "none")

pc13 <-ggplot(gatk_filteredv3_pca, aes(x=PC1, y=PC3, color=pop)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC1 (30.52%)") + ylab("PC3 (4.46%)") +
  theme_classic() +  
  scale_color_manual(values = mycol.pop) +
  theme(legend.position = "none")

pc23 <-ggplot(gatk_filteredv3_pca, aes(x=PC2, y=PC3, color=pop)) + 
  geom_point(size=5, alpha=0.3) + 
  xlab("PC2 (22.09%)") + ylab("PC3 (4.46%)") +
  theme_classic() +  
  scale_color_manual(values = mycol.pop) +
  theme(legend.position = "none")

ggarrange(pc12,pc13,pc23, 
          nrow = 1, 
          ncol = 3, 
          common.legend = TRUE)
```
